language: java
jdk:
  - openjdk8

services:
  - docker

# Pre-testing installs
install:
  - echo "installed nothing....."

# Scripts to be run such as tests
before_script:
  - echo "before script is nothiiiiing...."

script:
  - mvn clean install
  - docker --version # print the version for logging
  - docker build -t student-docker-maven.jar .
  - docker tag student-docker-maven.jar thiethaa/student-docker-maven:v.1.3.3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thiethaa/student-docker-maven:v.1.3.3
