language: java
jdk:
  - openjdk8

services:
  - docker

# Pre-testing installs
install:
  - echo "installed nothing....."

# Scripts to be run such as tests
before_script:
  - echo "before script is nothiiiiing...."

script:
  - mvn clean install

